package com.novelforge.app.util

import android.content.ContentValues
import android.content.Context
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import com.novelforge.app.data.model.Chapter
import com.novelforge.app.data.model.Novel
import java.io.File
import java.io.FileOutputStream

object NovelExporter {

    fun buildExportContent(novel: Novel, chapters: List<Chapter>): String {
        return buildString {
            appendLine("《${novel.title}》")
            appendLine("类型：${novel.genre}")
            appendLine()
            appendLine("【主角设定】")
            appendLine(novel.characterSetting)
            appendLine()
            appendLine("【世界观设定】")
            appendLine(novel.worldSetting)
            appendLine()
            appendLine("=".repeat(50))
            appendLine()

            chapters.sortedBy { it.order }.forEach { chapter ->
                appendLine("【${chapter.title}】")
                appendLine()
                appendLine(chapter.content)
                appendLine()
                appendLine("-".repeat(30))
                appendLine()
            }

            appendLine()
            appendLine("=".repeat(50))
            appendLine("Generated by NovelForge")
        }
    }

    fun saveToDownloads(context: Context, fileName: String, content: String): Boolean {
        return try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                val contentValues = ContentValues().apply {
                    put(MediaStore.Downloads.DISPLAY_NAME, fileName)
                    put(MediaStore.Downloads.MIME_TYPE, "text/plain")
                    put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
                }
                val resolver = context.contentResolver
                val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                uri?.let {
                    resolver.openOutputStream(it)?.use { outputStream ->
                        outputStream.write(content.toByteArray())
                    }
                    true
                } ?: false
            } else {
                @Suppress("DEPRECATION")
                val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
                val file = File(downloadsDir, fileName)
                FileOutputStream(file).use { outputStream ->
                    outputStream.write(content.toByteArray())
                }
                true
            }
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }
}
